filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/mylogs/*.log

output.logstash:
  hosts: ["logstash:5044"]

# output.elasticsearch:
#   hosts: ["elasticsearch:9200"]
#   username: "elastic"
#   password: ${ELASTIC_PASSWORD}
